version: '2'
services:
  redis:
    image: redis:3.2.9-alpine
    expose:
      - 6379
  server:
    build: ./server
    image: ranking:sge
    ports:
      - 8000:8000
    links:
      - redis:db
    command: gunicorn api:api -b 0.0.0.0:8000
